apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: "user17.azurecr.io/user:latest"
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV  # ConfigMap에서 환경 변수 주입
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: APP_ENV
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: APP_DEBUG            
            - name: API_KEY # Secret에서 환경 변수 주입 (API 키 사용)
              valueFrom:
                secretKeyRef:
                  name: user-api-secret
                  key: API_KEY            
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
